export const REQUEST_POSTS = 'REQUEST_POSTS';
export const REQUEST_POSTS_FAILED = 'REQUEST_POSTS_FAILED';
export const REQUEST_POSTS_SUCCEED = 'REQUEST_POSTS_SUCCEED';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
