export const REQUEST_POSTS = 'REQUEST_POSTS';
export const REQUEST_POSTS_FAILED = 'REQUEST_POSTS_FAILED';
export const REQUEST_POSTS_SUCCEED = 'REQUEST_POSTS_SUCCEED';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const REQUEST_REQUEST = 'REQUEST_REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
